# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
android.jdk.image=false
android.useJdkImage=false
org.gradle.daemon=false
org.gradle.configuration-cache=false
kotlin.code.style=official
android.newDsl=false
android.builtInKotlin=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL
android.suppressUnsupportedCompileSdk=37.0
kotlin.jvm.target.validation.mode=warning
android.uniquePackageNames=false
